//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TerminerstellungEntities : DbContext
    {
        public TerminerstellungEntities()
            : base("name=TerminerstellungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Bike> Bike { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Hardware> Hardware { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
    }
}
