//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminplanungFahrradladen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Length { get; set; }
        public decimal AppointmentPrice { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> WorkshopID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
